[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "homeship"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.136",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.2",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
]

[project.optional-dependencies]
dev = ["pytest>=8.0", "pylint>=3.0"]

[project.urls]
"Source Code" = "https://github.com/yanucodes/HomeShip"