"""add distance to ships

Revision ID: 8116bdb9269e
Revises: b000c0124de1
Create Date: 2026-06-12 21:24:28.738021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8116bdb9269e'
down_revision: Union[str, Sequence[str], None] = 'b000c0124de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows don't violate NOT NULL.
    op.add_column('ships', sa.Column('distance', sa.Float(), nullable=True))
    # Backfill existing rows with a starting distance of zero.
    op.execute('UPDATE ships SET distance = 0')
    # Now enforce NOT NULL once every row has a value.
    op.alter_column('ships', 'distance', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'distance')
    # ### end Alembic commands ###
