"""initial schema

Revision ID: 9a2b9fb1697e
Revises:
Create Date: 2026-05-26 19:40:09.815235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2b9fb1697e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('ship_id', sa.UUID(), nullable=False),
    sa.Column('shipname', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ship_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ship_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ship_id')
    )
    op.create_table('supplies',
    sa.Column('supply_id', sa.UUID(), nullable=False),
    sa.Column('ship_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('alert_state', sa.Enum('inactive', 'green', 'yellow', 'red', 'auto-destruct', name='alert_state'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('supply_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('ship_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Interval(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('date_last', sa.Date(), nullable=True),
    sa.Column('date_due', sa.Date(), nullable=True),
    sa.Column('alert_state', sa.Enum('inactive', 'green', 'yellow', 'red', 'auto-destruct', name='alert_state'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('supplies')
    op.drop_table('ship_members')
    op.drop_table('users')
    op.drop_table('ships')
    sa.Enum(name='alert_state').drop(op.get_bind())
    # ### end Alembic commands ###
